### ISSUE TITLE
Enable management policies

### ISSUE THREAD

**Issue by MrVinkel** [crossplane-contrib/provider-pagerduty#28]
### What problem are you facing?

I'm trying to use the [initProvider](https://docs.crossplane.io/latest/concepts/managed-resources/#initprovider) and [managementPolicies](https://docs.crossplane.io/latest/concepts/managed-resources/#managementpolicies) alpha features, but they are currently not supported by the pagerduty provider. I know it is an alpha feature, but as far as I can see it will promoted to a [beta feature](https://github.com/crossplane/crossplane/issues/4126) in crossplane v1.14.

Currently it is very confusing because the pagerduty provider logs that the feature is enable at startup, but then logs it is not enabled when trying to use it:

```txt
2023-08-29T10:22:07Z    INFO    provider-pagerduty    Alpha feature enabled    {"flag": "EnableAlphaManagementPolicies"} 
2023-08-29T10:22:08Z    DEBUG    events    `spec.managementPolicies` is set to a non-default value but the feature is not enabled: [Observe Create] 
```

Are there any plans to support this feature?

### How could PagerDuty Provider help solve your problem?

The Upjet generator already supports [management policies](https://github.com/upbound/upjet/blob/main/docs/adding-support-for-observe-only.md)

**Comment by haarchri** [comment]
let me check this - we added latest upjet version for managementPolicies and the feature flag in v0.5.0

**Comment by haarchri** [comment]
@MrVinkel can you try v0.6.1 ?

**Comment by MrVinkel** [comment]
I have tested it and it works now. Thank you for the fast response :)
